name: textmining-labs
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - nb_conda=2.2.1
  - scikit-learn=0.20.2
  - pandas=0.23.0
  - seaborn=0.9.0
  - gensim=3.4.0
  - spacy=2.0.18
  - wordcloud==1.5.0
  - tornado<6
  - pip:
    - pyLDAvis==2.1.2 
